######################################################################
# Automatically generated by qmake (3.0) Wed Apr 12 14:03:36 2017
######################################################################

TEMPLATE = app
TARGET = SignalsAndSlots
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
