######################################################################
# Automatically generated by qmake (3.0) Wed Apr 12 16:06:21 2017
######################################################################

TEMPLATE = app
TARGET = HelloQML
INCLUDEPATH += .

QT += quick

# Input
SOURCES += main.cpp
RESOURCES += qml.qrc
