######################################################################
# Automatically generated by qmake (3.0) Wed Apr 12 10:35:44 2017
######################################################################

TEMPLATE = app
TARGET = HelloGUI
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
