######################################################################
# Automatically generated by qmake (3.0) Wed Apr 12 10:08:51 2017
######################################################################

TEMPLATE = app
TARGET = Hello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
